# Generated by Django 4.2.11 on 2024-04-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neurodiversity',
            options={'verbose_name_plural': 'Neurodiversities'},
        ),
        migrations.RenameField(
            model_name='neurodiversity',
            old_name='nerodiversity',
            new_name='neurodiversity',
        ),
    ]
