# Generated by Django 4.2.11 on 2024-04-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_about_me_userprofile_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_on']},
        ),
    ]
